### ISSUE TITLE
感觉接口好像有点问题，但是不知道原因

### ISSUE THREAD

**Issue by YuGer26** [chenlongqiang/easy-short-url#2]
type: to_short
content: https://www.baidu.com
access_key: esu

回 not access
尝试了大佬的网站直接请求也是一样

**Comment by chenlongqiang** [comment]
因为我没有对 www.baidu.com 这个域名授权，授权表在 esu_access
我的自己搭的站点，暂时只对 lukachen.com、s.lukachen.com 授权
你用 content: http://lukachen.com/time 试试就知道了

**Comment by YuGer26** [comment]
我瞬间明白了意思了，比如我新建一个授权给baidu.com，我就可以缩短baidu.com/xxx了，感谢大佬
