### ISSUE TITLE
不知道啥情况，现在又报新的错了

### ISSUE THREAD

**Issue by YuGer26** [chenlongqiang/easy-short-url#3]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'access_key' in 'field list'

**Comment by chenlongqiang** [comment]
请按文档走一遍~ 
弄好配置、数据库啥的。

**Comment by YuGer26** [comment]
试了一下还是报错这个，估计是数据库问题，问题是.env里写的对的，数据库里也对的

**Comment by chenlongqiang** [comment]
问题就在数据库哈，排查确认一下~

**Comment by chenlongqiang** [comment]
https://github.com/chenlongqiang/easy-short-url/commit/54cb8af39a7f82d937cdcd73ac4abcd6e7dec555

回想起来，你提到的报错 @YuGer26 看一下，这个数据表的字段
