### ISSUE TITLE
不能微信里面使用，还要你何用？

### ISSUE THREAD

**Issue by zxg365zxg** [chenlongqiang/easy-short-url#5]
不能直接跳转，还要授权，还要你何用????别发上来占用公共资源，删了吧

**Comment by chenlongqiang** [comment]
为什么说 ”不要跟傻逼争论，他会把你拉到他的水平上，然后用他丰富的经验打败你”

**Comment by insoxin** [comment]
> 为什么说 ”不要跟傻逼争论，他会把你拉到他的水平上，然后用他丰富的经验打败你”

这傻逼,还跑到我项目里骂了,傻逼小学生一个,代码都不看

![image](https://user-images.githubusercontent.com/19371836/168029692-42a94d89-8af5-4e55-bac1-8f94fd56a9c6.png)
![image](https://user-images.githubusercontent.com/19371836/168029738-68fc7a59-3b3b-42d1-aca7-57295ea6e8b1.png)
新注册的号,连大号都不敢上
